routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


/*************************INICIO PÀGINA INICIAL***************/
Route::get('/', 'PageController@index')->name('page.index');

Route::get('/pesquisa', 'PageController@pesquisa')->name('page.pesquisa');
Route::get('/desenvolvimento', 'PageController@desenvolvimento')->name('page.desenvolvimento');
Route::get('/prototipo', 'PageController@prototipo')->name('page.prototipo');
Route::get('/mercado', 'PageController@mercado')->name('page.mercado');

Route::get('/banner/{id}/show', 'PageController@show')->name('page.show');

Route::get('/home', 'HomeController@index')->name('home.index');
/*************************FIM PÀGINA INICIAL***************/


/*************************INICIO ADMIN CATEGORIA***************/
Route::resource('categoria', 'CategoryController');
/*************************FIM ADMIN CATEGORIA***************/

/*************************INICIO ADMIN PROJETO***************/
Route::resource('projeto', 'ProjectController');
/*************************FIM ADMIN PROJETO***************/

/*************************INICIO ADMIN NIT***************/
Route::resource('nit', 'NitController');

/*************************FIM ADMIN NIT***************/

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['categoria_id','nit_id','nome','problema','solucao','beneficio','oportunidade','contato','estagio','diferencial','mercado','imagem'];

    public function category()
    {
        return $this->belongsTo(Category::class,'categoria_id');
    }

    public function user()
    {
        return $this->belongsTo(Category::class,'nit_id');
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\ProjectRequest;
use App\Http\Requests\ProjectUpdateRequest;
use App\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectController extends Controller
{


    /**
     * @var Project
     */
    private $project;
    /**
     * @var Category
     */
    private $category;

    public function __construct(Project $project, Category $category)
    {
        $this->project = $project;
        $this->category = $category;
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @return Project
     */
    public function getProject()
    {
        return $this->project;
    }


    public function index()
    {
        $nit_id = Auth::user()->id;

        $projects = $this->getProject()->where('nit_id',$nit_id)->paginate(5);

        $categories = $this->getCategory()->all()->pluck('categoria','id');

        return view('projects.index',compact('projects','categories'));
    }


    public function store(ProjectRequest $request)
    {
        $hash = rand(100,10000);

        $data_arquivo					= date('Ymd');
        $nome_arquivo 					= $data_arquivo.'_'.$hash.'.png';

        $project = new Project(array(
            'categoria_id' => $request->get('categoria_id'),
            'nit_id'  => $request->get('nit_id'),
            'nome'  => $request->get('nome'),
            'problema'  => $request->get('problema'),
            'solucao'  => $request->get('solucao'),
            'beneficio'  => $request->get('beneficio'),
            'oportunidade'  => $request->get('oportunidade'),
            'contato'  => $request->get('contato'),
            'estagio'  => $request->get('estagio'),
            'diferencial'  => $request->get('diferencial'),
            'mercado'  => $request->get('mercado'),
            'imagem'  => $nome_arquivo

        ));

        $project->save();

        $request->file('imagem')->move(public_path().'/uploads',$project->imagem);

        return redirect()->route('projeto.index')->with('message','Projeto cadastrado com sucesso!');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $project = $this->getProject()->find($id);
        $categories = $this->getCategory()->all()->pluck('categoria','id');
        return view('projects.edit', compact('project','categories'));

    }

    public function update(ProjectUpdateRequest $request, $id)
    {
        $this->getProject()->find($id)->update($request->all());
        return redirect()->route('projeto.index');
    }

    public function destroy($id)
    {
        $this->getProject()->find($id)->delete();
        return redirect()->route('projeto.index');

    }
}

resources/views/projects/_form.blade.php
<div>
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <div id="error"></div>

    {{ Form::hidden('nit_id',Auth::user()->id) }}

    <div class="form-group">
        <label for="name" class="control-label">Categoria</label>
        <div>
            {{ Form::select('categoria_id',$categories,null,['class'=>'form-control','id'=>'categoria_id','placeholder'=>'Selecione uma Categoria']) }}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Nome</label>
        <div>
            {!! Form::text('nome', null, ['class' => 'form-control', 'placeholder' => 'Nome', 'id' => 'nome']) !!}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Problema</label>
        <div>
            {!! Form::text('problema', null, ['class' => 'form-control', 'placeholder' => 'Categoria', 'id' => 'categoria']) !!}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Solucao</label>
        <div>
            {!! Form::text('solucao', null, ['class' => 'form-control', 'placeholder' => 'Solucao', 'id' => 'solucao']) !!}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Beneficio</label>
        <div>
            {!! Form::text('beneficio', null, ['class' => 'form-control', 'placeholder' => 'Beneficio', 'id' => 'beneficio']) !!}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Oportunidade</label>
        <div>
            {!! Form::text('oportunidade', null, ['class' => 'form-control', 'placeholder' => 'Oportunidade', 'id' => 'oportunidade']) !!}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Contato</label>
        <div>
            {!! Form::text('contato', null, ['class' => 'form-control', 'placeholder' => 'Contato', 'id' => 'contato']) !!}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Estagio</label>
        <div>
            {!! Form::select('estagio',['1'=>'Pesquisa','2'=>'Desenvolvimento','3'=>'Protótipo','4'=>'Mercado'], null,['class' => 'form-control', 'placeholder' => 'Estagio', 'id' => 'estagio']) !!}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Diferencial</label>
        <div>
            {!! Form::text('diferencial', null, ['class' => 'form-control', 'placeholder' => 'Diferencial', 'id' => 'diferencial']) !!}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Mercado</label>
        <div>
            {!! Form::text('mercado', null, ['class' => 'form-control', 'placeholder' => 'Mercado', 'id' => 'mercado']) !!}
        </div>
    </div>

    <div class="form-group">
        <label for="name" class="control-label">Imagem</label>
        <div>
            {!! Form::file('imagem',null,['class' => 'form-control', 'placeholder' => 'Imagem', 'id' => 'imagem']) !!}
        </div>
    </div>
</div>

resources/views/projects/edit.blade.php
@extends('layouts.base')

@section('nav')
    @include('layouts.partials.menu')
@endsection

@section('content')
<div class="container">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Edição de Projetos
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('home.index')}}"> Inicial</a></li>
            <li><a href="{{ route('projeto.index')}}"> Projetos</a></li>
            <li>Edição</li>
        </ol>
    </section>
    <div>
        @if($errors->any())
            <div class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <p>{{$error}}</p>
                @endforeach
            </div>
        @endif
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    {!! Form::model($project,[
                        'route'=>['projeto.update', $project->id],
                        'method' => 'put',
                        'files' => true
                        ])
                        !!}
                    @include('projects._form')
                    <div class="content">
                        <a href="{{ route('projeto.index') }}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Voltar </a>
                        <button type="submit" class="btn btn-primary pull-right"> <i class="fa fa-floppy-o"></i> Salvar</button>
                    </div>
                    {!! Form::close() !!}

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
</div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.base')

@section('nav')
    @include('layouts.partials.menu')
@endsection

@section('content')
<div class="container">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Listagem de Projetos
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('home.index')}}"> Inicial</a></li>
            <li class="active">Projetos</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Projetos cadastradas</h3>
                <div>
                    @if($errors->any())
                        <div class="alert alert-danger">
                            @foreach($errors->all() as $error)
                                <p>{{$error}}</p>
                            @endforeach
                        </div>
                    @endif
                </div>
                <div class="box-tools">
                    <a href="#" class="btn btn-info pull-right" data-toggle="modal" data-target="#modalcreate"><i class="fa fa-plus"> </i> Novo Projeto</a>
                </div>
            </div>
            <div class="box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>Criado em</th>
                        <th>Atualizado em</th>
                        <th style="width: 5px;" colspan="2" class="text-center">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if($projects)
                        @foreach($projects as $project)
                            <tr>
                                <td>{{ $project->id }}</td>
                                <td>{{ $project->nome }}</td>
                                <td>{{ $project->created_at->format('d/m/Y') }}</td>
                                <td>{{ $project->updated_at->format('d/m/Y') }}</td>
                                <td  style="width: 5px;">
                                    <a href='{{ route('projeto.edit', ['id'=>$project->id])}}' class="btn btn-action btn-info"><i class="fa fa-edit"></i></a>
                                </td>
                                <td  style="width: 5px;">
                                    <a href="#modal_delete-{{$project->id}}" class="btn btn-danger" data-toggle="modal"><i class="fa fa-trash-o"></i></a>

                                    {{-- modal delete --}}
                                    <div class="modal fade" id="modal_delete-{{ $project->id}}" data-backdrop='false'>
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                    <h4 class="modal-title">Deletar Projeto</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <h3 class="text-center text-danger" > Tem certeza que deseja deletar esta projeto?</h3>
                                                    <div class="row">
                                                        <div class="col-md-6 ">  <button type="button" class="btn btn-default btn-block" data-dismiss="modal">Não</button> </div>
                                                        <div class="col-md-6 ">
                                                            {!! Form::open(['route'=>['projeto.destroy', $project->id], 'method' => 'delete']) !!}
                                                            {!! Form::submit('Sim',['class'=>'btn  btn-danger btn-block']) !!}
                                                            {!! Form::close() !!}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="5">Não há dados para exibir</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                {{ $projects->render() }}
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->


<!-- Modal Cadastro de Projeto -->
<div class="modal fade" id="modalcreate" tabindex="-1" role="dialog" aria-labelledby="modalcreateLabel" data-backdrop="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalcreateLabel">Cadastro de Projeto</h4>
            </div>
            <div class="modal-body">
                {!! Form::open(array('route' => 'projeto.store','class' => 'form','novalidate' => 'novalidate','files' => true)) !!}
                @include('projects._form')

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal"> <i class="fa fa-close"></i> Cancelar</button>
                <button type="submit" class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Salvar</button>
                {!! Form::close() !!}

            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Blank page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Title</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                Start creating your amazing application!
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                Footer
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->

@endsection