routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


/*************************INICIO PÀGINA INICIAL***************/
Route::get('/', 'PageController@index')->name('page.index');

Route::get('/pesquisa', 'PageController@pesquisa')->name('page.pesquisa');
Route::get('/desenvolvimento', 'PageController@desenvolvimento')->name('page.desenvolvimento');
Route::get('/prototipo', 'PageController@prototipo')->name('page.prototipo');
Route::get('/mercado', 'PageController@mercado')->name('page.mercado');

Route::get('/banner/{id}/show', 'PageController@show')->name('page.show');

Route::get('/home', 'HomeController@index')->name('home.index');
/*************************FIM PÀGINA INICIAL***************/


/*************************INICIO ADMIN CATEGORIA***************/
Route::resource('categoria', 'CategoryController');
/*************************FIM ADMIN CATEGORIA***************/

/*************************INICIO ADMIN PROJETO***************/
Route::resource('projeto', 'ProjectController');
/*************************FIM ADMIN PROJETO***************/

/*************************INICIO ADMIN NIT***************/
Route::resource('nit', 'NitController');

/*************************FIM ADMIN NIT***************/

resources/views/layouts/partials/head.blade.php
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@yield('title')</title>

    <!-- Bootstrap -->

    <link rel="stylesheet" type="text/css" href=" {{ asset('assets/bootstrap/css/bootstrap.css') }}" />
    <link rel="stylesheet" type="text/css" href=" {{ asset('assets/custom/css/app.css') }}" />


    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <script src="{{ asset('plugin/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('plugin/fontawesome/fontawesome.js') }}"></script>
    <script src="{{ asset('assets/custom/js/app.js') }}"></script>


</head>

resources/views/layouts/partials/menu.blade.php
<div class="container-fluid">

    <div class="container-fluid">

        <!-- Nome do projeto -->
        <div class="navbar-header">
            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastros <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{route('categoria.index')}}">Categoria</a></li>
                        <li><a href="{{route('projeto.index')}}">Projeto</a></li>
                        <li><a href="{{ route('nit.index') }}">Nit</a></li>
                    </ul>
                </li>
            </ul>


            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            @if(!Auth::guest())
                                {{ Auth::user()->name }} <span class="caret"></span>
                            @endif

                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Sair
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>


</div>