routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


/*************************INICIO PÀGINA INICIAL***************/
Route::get('/', 'PageController@index')->name('page.index');

Route::get('/pesquisa', 'PageController@pesquisa')->name('page.pesquisa');
Route::get('/desenvolvimento', 'PageController@desenvolvimento')->name('page.desenvolvimento');
Route::get('/prototipo', 'PageController@prototipo')->name('page.prototipo');
Route::get('/mercado', 'PageController@mercado')->name('page.mercado');

Route::get('/banner/{id}/show', 'PageController@show')->name('page.show');

Route::get('/home', 'HomeController@index')->name('home.index');
/*************************FIM PÀGINA INICIAL***************/


/*************************INICIO ADMIN CATEGORIA***************/
Route::resource('categoria', 'CategoryController');
/*************************FIM ADMIN CATEGORIA***************/

/*************************INICIO ADMIN PROJETO***************/
Route::resource('projeto', 'ProjectController');
/*************************FIM ADMIN PROJETO***************/

/*************************INICIO ADMIN NIT***************/
Route::resource('nit', 'NitController');

/*************************FIM ADMIN NIT***************/

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['categoria'];

    public function projects()
    {
        return $this->hasMany(Project::class,'categoria_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CategoryRequest;
use App\Http\Requests\CategoryUpdateRequest;


class CategoryController extends Controller
{

    /**
     * @var Category
     */
    private $category;

    public function __construct(Category $category)
    {

        $this->category = $category;
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }



    public function index()
    {
        $categories = $this->getCategory()->paginate(5);

        return view('categories.index',compact('categories'));
    }


    public function store(CategoryRequest $request)
    {
        $this->getCategory()->create($request->all());

        return redirect()->route('categoria.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $category = $this->getCategory()->find($id);
        return view('categories.edit', compact('category'));

    }

    public function update(CategoryUpdateRequest $request, $id)
    {
        $this->getCategory()->find($id)->update($request->all());
        return redirect()->route('categoria.index');
    }

    public function destroy($id)
    {
        $this->getCategory()->find($id)->delete();
        return redirect()->route('categoria.index');

    }


}

resources/views/categories/_form.blade.php
<div>
    <div id="error"></div>
    <div class="form-group">
        <label for="name" class="control-label">Nome</label>
        <div>
            {!! Form::text('categoria', null, ['class' => 'form-control', 'placeholder' => 'Categoria', 'id' => 'categoria']) !!}
        </div>
    </div>
</div>

resources/views/categories/edit.blade.php
@extends('layouts.base')

@section('nav')
    @include('layouts.partials.menu')
@endsection

@section('content')

<div class="container">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Edição de Categorias
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('home.index')}}"> Inicial</a></li>
            <li><a href="{{ route('categoria.index')}}"> Categorias</a></li>
            <li>Edição</li>
        </ol>
    </section>
    <div>
        @if($errors->any())
            <div class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <p>{{$error}}</p>
                @endforeach
            </div>
        @endif
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    {!! Form::model($category,[
                        'route'=>['categoria.update', $category->id],
                        'method' => 'put',
                        'files' => true
                        ])
                        !!}
                    @include('categories._form')
                    <div class="content">
                        <a href="{{ route('categoria.index') }}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Voltar </a>
                        <button type="submit" class="btn btn-primary pull-right"> <i class="fa fa-floppy-o"></i> Salvar</button>
                    </div>
                    {!! Form::close() !!}

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
</div>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.base')

@section('nav')
    @include('layouts.partials.menu')
@endsection

@section('content')
<div class="container">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Listagem de Categorias
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('home.index')}}"> Inicial</a></li>
            <li class="active">Categorias</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Categorias cadastradas</h3>
                <div>
                    @if($errors->any())
                        <div class="alert alert-danger">
                            @foreach($errors->all() as $error)
                                <p>{{$error}}</p>
                            @endforeach
                        </div>
                    @endif
                </div>
                <div class="box-tools">
                    <a href="#" class="btn btn-info pull-right" data-toggle="modal" data-target="#modalcreate"><i class="fa fa-plus"> </i> Nova categoria</a>
                </div>
            </div>
            <div class="box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>Criado em</th>
                        <th>Atualizado em</th>
                        <th style="width: 5px;" colspan="2" class="text-center">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if($categories)
                        @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->id }}</td>
                                <td>{{ $category->categoria }}</td>
                                <td>{{ $category->created_at->format('d/m/Y') }}</td>
                                <td>{{ $category->updated_at->format('d/m/Y') }}</td>
                                <td  style="width: 5px;">
                                    <a href='{{ route('categoria.edit', ['id'=>$category->id])}}' class="btn btn-action btn-info"><i class="fa fa-edit"></i></a>
                                </td>
                                <td  style="width: 5px;">
                                    <a href="#modal_delete-{{$category->id}}" class="btn btn-danger" data-toggle="modal"><i class="fa fa-trash-o"></i></a>

                                    {{-- modal delete --}}
                                    <div class="modal fade" id="modal_delete-{{ $category->id}}" data-backdrop='false'>
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                    <h4 class="modal-title">Deletar Categoria</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <h3 class="text-center text-danger" > Tem certeza que deseja deletar esta categoria?</h3>
                                                    <div class="row">
                                                        <div class="col-md-6 ">  <button type="button" class="btn btn-default btn-block" data-dismiss="modal">Não</button> </div>
                                                        <div class="col-md-6 ">
                                                            {!! Form::open(['route'=>['categoria.destroy', $category->id], 'method' => 'delete']) !!}
                                                            {!! Form::submit('Sim',['class'=>'btn  btn-danger btn-block']) !!}
                                                            {!! Form::close() !!}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="5">Não há dados para exibir</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                {{ $categories->render() }}
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->


<!-- Modal Cadastro de Categoria -->
<div class="modal fade" id="modalcreate" tabindex="-1" role="dialog" aria-labelledby="modalcreateLabel" data-backdrop="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalcreateLabel">Cadastro de Categoria</h4>
            </div>
            <div class="modal-body">
                {!! Form::open([route('categoria.store')]) !!}
                @include('categories._form')

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal"> <i class="fa fa-close"></i> Cancelar</button>
                <button type="submit" class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Salvar</button>
                {!! Form::close() !!}

            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Blank page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Title</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                Start creating your amazing application!
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                Footer
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->

@endsection